"""MongoDB layer: client lifecycle, collection accessors, document schemas."""

from app.core.db.client import (
    SETTINGS_DOC_ID,
    close_db,
    get_db,
    init_db,
    ip_pool_col,
    lab_invites_col,
    plan_runs_col,
    project_shares_col,
    projects_col,
    settings_col,
    users_col,
    vm_registry_col,
)
from app.core.db.models import (
    LabInviteDoc,
    MongoModel,
    ProjectDoc,
    SettingsDoc,
    UserDoc,
    Viewport,
    VmRegistryEntry,
    from_mongo,
    now_ms,
    to_mongo,
)

__all__ = [
    "SETTINGS_DOC_ID",
    "close_db",
    "get_db",
    "init_db",
    "ip_pool_col",
    "lab_invites_col",
    "plan_runs_col",
    "project_shares_col",
    "projects_col",
    "settings_col",
    "users_col",
    "vm_registry_col",
    "LabInviteDoc",
    "MongoModel",
    "ProjectDoc",
    "SettingsDoc",
    "UserDoc",
    "Viewport",
    "VmRegistryEntry",
    "from_mongo",
    "now_ms",
    "to_mongo",
]
